### ISSUE TITLE
Header files missing.

### ISSUE THREAD

**Issue by rajesh-alla** [DashW/Ingenuity#1]
Hi I tried to compile the code but found that Leap.h, Vector3.h,  and Spout.h files are missing. Request you to provide the same.
Thanks.

**Comment by DashW** [comment]
Leap.h and Vector3.h are part of the Leap Motion SDK which can be downloaded from https://developer.leapmotion.com/

Spout.h is part of the Spout2 library which can be downloaded from https://github.com/leadedge/Spout2

The Ingenuity Visual Studio Project will likely need to be modified to point to their install directories.

Please be aware that Ingenuity is a single developer's side-project. It is no longer maintained and has not been updated in almost a decade, and in that time these SDKs may have introduced breaking changes that may need to be worked around.

If you are looking to get started with a small game engine, I would highly recommend not using Ingenuity and trying alternatives like Panda3D (https://www.panda3d.org/features/) or Google Filament (https://google.github.io/filament/)
________________________________
From: rajesh-alla ***@***.***>
Sent: 26 June 2023 14:42
To: DashW/Ingenuity ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DashW/Ingenuity] Header files missing. (Issue #1)


Hi I tried to compile the code but found that Leap.h, Vector3.h, and Spout.h files are missing. Request you to provide the same.
Thanks.

**Comment by rajesh-alla** [comment]
Thanks a ton for that prompt reply and valuable suggestion. Will certainly re-evaluate based on your suggestion. Thankyou once again.
-Rajesh
